### ISSUE TITLE
Failed to execute ``collectd-storj-exec-plugin'': No such file or directory

### ISSUE THREAD

**Issue by timXTM** [bobey/storj-collectd-plugin#2]
After installing the plugin and updating the configuration file according to the readme, I get the following error when I run:

`sudo systemctl status collectd`

exec plugin: Failed to execute ``collectd-storj-exec-plugin'': No such file or directory

Any advice? I enjoyed your blog post on storj monitoring!

**Comment by obalais** [comment]
Thanks for your feedback. Did you run `npm install -g storj-collectd-plugin`?

If you did so, what happen when you run the command `collectd-storj-exec-plugin` with your user?

**Comment by timXTM** [comment]
I figured it out. I needed to put the path to the
collectd-storj-exec-plugin in the exec portion of the config file. My
mistake. Now it's working great.

Tim

2017年5月24日 上午3:43，"Olivier Balais" <notifications@github.com>写道：

**Comment by gsfakianakis** [comment]
I have the same problem.
If I run collectd-storj-exec-plugin, then it seems like it is running. No message and I need to control+C to type again.

I used the path: /home/username/.nvm/versions/node/v6.10.3/bin/collectd-storj-exec-plugin
but now I get error:
exec plugin: exec_read_one: error = /usr/bin/env: ‘node’: No such file or directory

Any ideas ?

**Comment by t0maten** [comment]
Same here. cant find plugin after install.
ubuntu 16.04

**Comment by AlexR2106** [comment]
Got also Problems with running this tool (No such file or directory, Access denied)
I was able to solve it by creating an sh file, which calls the script:

/home/USER/.nvm/versions/node/v6.11.1/bin/node /home/USER/.nvm/versions/node/v6.11.1/lib/node_modules/storj-collectd-plugin

This worked out fine for me.

**Comment by obalais** [comment]
If you installed the plugin globally, it should be available by running `collectd-storj-exec-plugin`.

If it's not, place the full path to the plugin binary in your collectd config.

Does it work in that case?

**Comment by p0ntsNL** [comment]
I have the same, with absolute path towards the plugin the following error occur:

`==> syslog <==
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error = /home/stefan/.nvm/versions/node/v6.11.2/lib/node_modules/storj-collectd-plugin/node_modules/bindings/bindings.js:88
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =         throw e
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =         ^
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error = Error: Module version mismatch. Expected 46, got 48.
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at Error (native)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at Object.Module._extensions..node (module.js:434:18)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at Module.load (module.js:343:32)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at Function.Module._load (module.js:300:12)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at Module.require (module.js:353:17)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at require (internal/module.js:12:17)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at bindings (/home/stefan/.nvm/versions/node/v6.11.2/lib/node_modules/storj-collectd-plugin/node_modules/bindings/bindings.js:81:44)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at Object.<anonymous> (/home/stefan/.nvm/versions/node/v6.11.2/lib/node_modules/storj-collectd-plugin/node_modules/weak/lib/weak.js:7:35)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at Module._compile (module.js:409:26)
Aug 14 08:26:10 storj collectd[30449]: exec plugin: exec_read_one: error =     at Object.Module._extensions..js (module.js:416:10)`

**Comment by timXTM** [comment]
I also am having problems again with this. I set up a new node and can't get the plugin to work. I installed the plugin globally, as directed, but it would not work - giving a "No such file or directory" error. Then I tried to use the direct path (See image below). Then I got a "Permission denied" error. I opened up the permissions fully for this directory with chmod 777, but it did not work - the "Permission denied" error persists. Any suggestions?

![image](https://user-images.githubusercontent.com/19766625/29270147-e9eee2c6-8127-11e7-8bb7-a08a7f45dd08.png)

**Comment by obalais** [comment]
It seems you have setup the plugin with the user `pi`. Did you thought of using the very same user in your collectd configuration?

```
# /etc/collectd/collectd.conf

LoadPlugin exec

<Plugin exec>
        Interval 120
        Exec "pi" "/path/to/collectd-storj-exec-plugin"
</Plugin>
```

**Comment by timXTM** [comment]
Wow, thanks for the quick reply!

Yes, the user is "pi" in the collectd.conf...

![image](https://user-images.githubusercontent.com/19766625/29270854-2f47d4a6-812b-11e7-9ccd-f5c48211bcf0.png)

**Comment by obalais** [comment]
Maybe try the following then:

```
LoadPlugin exec

<Plugin exec>
        Interval 120
        Exec "pi" "/path/to/nodejs" "/path/to/collectd-storj-exec-plugin"
</Plugin>
```

**Comment by p0ntsNL** [comment]
that worked, TY!

**Comment by timXTM** [comment]
Mine still won't go. Could this be related to using nvm rather than installing node directly? Perhaps the exec plugin doesn't play well with nvm? I think I did not use nvm on the last node I set up.

@p0nt Can you post what you put into the <Plugin exec> section of the collectd.conf?

Here's what I've got in my collectd.conf and I'm still getting the same "Permission denied" error:

![capture](https://user-images.githubusercontent.com/19766625/29274496-a90bfec0-813a-11e7-9652-e4cba61d4e57.PNG)

**Comment by p0ntsNL** [comment]
you should change to the absolute node path.

this is what I put in:

https://paste.xsnews.nl/view/O36n3GnlYyB3j

Also make sure to enable 'LoadPlugin exec' and 'LoadPlugin network'

also make sure that 'storj-collectd-plugin' is owned by the user executing it, for you that would be pi:

chown pi:pi /path/to/collectd-storj-exec-plugin
