### ISSUE TITLE
SyntaxError while running

### ISSUE THREAD

**Issue by pRizz** [bobey/storj-collectd-plugin#6]
From tailing `syslog`

```
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error = const dnode = require('dnode');
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error = ^^^^^
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error = SyntaxError: Use of const in strict mode.
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error =     at Module._compile (module.js:439:25)
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error =     at Object.Module._extensions..js (module.js:474:10)
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error =     at Module.load (module.js:356:32)
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error =     at Function.Module._load (module.js:312:12)
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error =     at Function.Module.runMain (module.js:497:10)
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error =     at startup (node.js:119:16)
Jul  4 01:17:15 raspberrypi collectd[2360]: exec plugin: exec_read_one: error =     at node.js:906:3```

**Comment by pRizz** [comment]
Had to update `node` as root
